[package]
name = "images_as_json"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.8", features = ["blocking"]}
serde = {version = "1.0.213", features = ["serde_derive"]}
serde_json = "1.0.132"
indicatif = "0.17.8"
rayon = "1.10.0"
bincode = "1.3.3"
